[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

# we having lua warnings with this one !!!
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''cover = dollar_UI.parent,'''
position = 'after'
payload = '''
scale = 0.5,
'''
match_indent = true
times = 1



# Vanilla
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local num_dollars = config.dollars or 1'''
position = 'after'
payload = '''
local num_scarab = config.scarabs or 0
if not config.dollars and num_scarab > 0 then
	num_dollars = 0
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''local dollar_row = 0'''
position = 'before'
payload = '''
local scarab_row = 0
if num_scarab > 60 then
	local dollar_string = localize('$') .. num_scarab
	G.E_MANAGER:add_event(Event({
		trigger = 'before',
		delay = 0.38,
		func = function()
			G.round_eval:add_child(
				{
					n = G.UIT.R,
					config = { align = "cm", id = 'scarab_row_' .. (scarab_row + 1) .. '_' .. config.name },
					nodes = {
						{ n = G.UIT.O, config = { object = DynaText({ string = { '造' .. num_scarab }, colours = { G.C.BLUE }, shadow = true, pop_in = 0, scale = 0.65, float = true }) } }
					}
				},
				G.round_eval:get_UIE_by_ID('dollar_' .. config.name))

			play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7)
			play_sound('coin6', 1.3, 0.8)
			return true
		end
	}))
elseif num_scarab > 0 then
	for i = 1, num_scarab or 1 do
		G.E_MANAGER:add_event(Event({
			trigger = 'before',
			delay = 0.18 - ((num_scarab > 20 and 0.13) or (num_scarab > 9 and 0.1) or 0),
			func = function()
				if i % 30 == 1 then
					G.round_eval:add_child(
						{ n = G.UIT.R, config = { align = "cm", id = 'scarab_row_' .. (scarab_row + 1) .. '_' .. config.name }, nodes = {} },
						G.round_eval:get_UIE_by_ID('dollar_' .. config.name))
					scarab_row = scarab_row + 1
				end

				local r = { n = G.UIT.T, config = { text = '造', colour = G.C.BLUE, scale = ((num_scarab > 20 and 0.28) or (num_scarab > 9 and 0.43) or 0.58), shadow = true, hover = true, can_collide = false, juice = true } }
				play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7 - (num_scarab > 20 and 0.2 or 0))

				G.round_eval:add_child(r, G.round_eval:get_UIE_by_ID('scarab_row_' .. (scarab_row) .. '_' .. config.name))
				G.VIBRATION = G.VIBRATION + 0.4
				return true
			end
		}))
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''elseif config.name == 'hands' then'''
position = 'before'
payload = '''
elseif config.name == 'boss_scarab_bonus' then
	table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = ' '..localize('k_payasaka_scarabene_bonus')..' ', colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.current_round.dollars = config.dollars'''
position = 'after'
payload = '''
G.GAME.current_round.pharahos_scarabs = config.scarabs or 0
'''
match_indent = true
times = 1

# Entropy, as that completely overrides add_round_eval_row
[[patches]]
[patches.pattern]
target = '''=[SMODS entr "lib/fixes.lua"]'''
pattern = '''local num_dollars = config.dollars or 1'''
position = 'after'
payload = '''
local num_scarab = config.scarabs or 0
if not config.dollars and num_scarab > 0 then
	num_dollars = 0
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS entr "lib/fixes.lua"]'''
pattern = '''local dollar_row = 0'''
position = 'before'
payload = '''
local scarab_row = 0
if num_scarab > 60 then
	local dollar_string = localize('$') .. num_scarab
	G.E_MANAGER:add_event(Event({
		trigger = 'before',
		delay = 0.38,
		func = function()
			G.round_eval:add_child(
				{
					n = G.UIT.R,
					config = { align = "cm", id = 'scarab_row_' .. (scarab_row + 1) .. '_' .. config.name },
					nodes = {
						{ n = G.UIT.O, config = { object = DynaText({ string = { '造' .. num_scarab }, colours = { G.C.BLUE }, shadow = true, pop_in = 0, scale = 0.65, float = true }) } }
					}
				},
				G.round_eval:get_UIE_by_ID('dollar_' .. config.name))

			play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7)
			play_sound('coin6', 1.3, 0.8)
			return true
		end
	}))
elseif num_scarab > 0 then
	for i = 1, num_scarab or 1 do
		G.E_MANAGER:add_event(Event({
			trigger = 'before',
			delay = 0.18 - ((num_scarab > 20 and 0.13) or (num_scarab > 9 and 0.1) or 0),
			func = function()
				if i % 30 == 1 then
					G.round_eval:add_child(
						{ n = G.UIT.R, config = { align = "cm", id = 'scarab_row_' .. (scarab_row + 1) .. '_' .. config.name }, nodes = {} },
						G.round_eval:get_UIE_by_ID('dollar_' .. config.name))
					scarab_row = scarab_row + 1
				end

				local r = { n = G.UIT.T, config = { text = '造', colour = G.C.BLUE, scale = ((num_scarab > 20 and 0.28) or (num_scarab > 9 and 0.43) or 0.58), shadow = true, hover = true, can_collide = false, juice = true } }
				play_sound('coin3', 0.9 + 0.2 * math.random(), 0.7 - (num_scarab > 20 and 0.2 or 0))

				G.round_eval:add_child(r, G.round_eval:get_UIE_by_ID('scarab_row_' .. (scarab_row) .. '_' .. config.name))
				G.VIBRATION = G.VIBRATION + 0.4
				return true
			end
		}))
	end
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS entr "lib/fixes.lua"]'''
pattern = '''elseif config.name == 'hands' then'''
position = 'before'
payload = '''
elseif config.name == 'boss_scarab_bonus' then
	table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = ' '..localize('k_payasaka_scarabene_bonus')..' ', colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS entr "lib/fixes.lua"]'''
pattern = '''G.GAME.current_round.dollars = config.dollars'''
position = 'after'
payload = '''
G.GAME.current_round.pharahos_scarabs = config.scarabs or 0
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''add_round_eval_row({name = 'bottom', dollars = dollars})'''
position = 'at'
payload = '''
local scarabs = 0

if G.GAME.blind and G.GAME.blind:get_type() == 'Boss' then
	add_round_eval_row({name = 'boss_scarab_bonus', bonus = true, scarabs = 1, pitch = pitch})
	scarabs = scarabs + 1
	pitch = pitch + 0.06
end

add_round_eval_row({name = 'bottom', dollars = dollars, scarabs = scarabs})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''ease_dollars(G.GAME.current_round.dollars)'''
position = 'after'
payload = '''
ease_scarab(G.GAME.current_round.pharahos_scarabs or 0)
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.previous_round.dollars = G.GAME.dollars'''
position = 'after'
payload = '''
G.GAME.previous_round.pharahos_scarabs = G.GAME.pharahos_scarabs
'''
match_indent = true
times = 1